export enum VNodeFlags {
  ELEMENT_HTML = 1,

  ELEMENT_SVG = 1 << 1,

  COMPONENT_STATEFUL_NORMAL = 1 << 2,

  COMPONENT_STATEFUL_SHOULD_KEEP_ALIVE = 1 << 3,

  COMPONENT_STATEFUL_KEPT_ALIVE = 1 << 4,

  COMPONENT_FUNCTIONAL = 1 << 5,

  TEXT = 1 << 6,

  FRAGMENT = 1 << 7,

  PORTAL = 1 << 8,
}

export enum ChildrenFlags {
  UNKNOWN_CHILDREN = 0,
  NO_CHILDREN = 1,
  SINGLE_VNODE = 1 << 1,
  KEYED_VNODES = 1 << 2,
  NONE_KEYED_VNODES = 1 << 3,
}